AWSTemplateFormatVersion: 2010-09-09
Description: 'Application layer of the PayID validator service.'
Parameters:
  paramAppServerAmiId:
    Type: AWS::EC2::Image::Id
    Default: ami-09d95fab7fff3776c
    Description: The EC2 AMI ID for the app server. This should be an Amazon Linux 2 AMI.
  paramAppServerKeyId:
    Type: AWS::EC2::KeyPair::KeyName
    Default: payid
    Description: The KeyPair name to use when SSH-ing into the instance.
  paramAppHostname:
    Type: String
    AllowedPattern: '(?!-)[a-zA-Z0-9-.]{1,63}(?<!-)'
    Default: test.payidvalidator.com
    Description: Hostname of the payid instance being served. (payidvalidator.com, test.payidvalidator.com, etc.)
  paramHostedRoute53ZoneId:
    Type: AWS::Route53::HostedZone::Id
    Default: Z0084357DZYO84SIVC94
    Description: The Route53 Zone ID to write the CNAME entry to when authorizing the certificate.
  paramEtherscanApiKey:
    Type: String
    Description: API Key provided by Etherscan.io
  paramBlockchaincomApiKey:
    Type: String
    Description: API Key provided by Blockchain.com

Resources:
  certificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName:
        !Ref paramAppHostname
      DomainValidationOptions:
        - DomainName: !Ref paramAppHostname
          HostedZoneId: !Ref paramHostedRoute53ZoneId
      ValidationMethod: DNS

  loadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      IpAddressType: ipv4
      Name: !Join
        - "-"
        - - "app"
          - !Select
            - 0
            - !Split
              - "-"
              - !Select
                - 2
                - !Split
                  - "/"
                  - !Ref "AWS::StackId"
      SecurityGroups:
        - Fn::ImportValue: securityGroupLoadBalancer
      Subnets:
        - Fn::ImportValue: infrastructureVpcSubnetIdA
        - Fn::ImportValue: infrastructureVpcSubnetIdB
        - Fn::ImportValue: infrastructureVpcSubnetIdC
      Type: application
  loadBalancerDefaultTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      HealthCheckEnabled: true
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 2
      Name: !Join
        - "-"
        - - "app"
          - !Select
            - 0
            - !Split
              - "-"
              - !Select
                - 2
                - !Split
                  - "/"
                  - !Ref "AWS::StackId"
      Port: 80
      Protocol: HTTP
      TargetGroupAttributes:
        - Key: stickiness.enabled
          Value: false
        - Key: deregistration_delay.timeout_seconds
          Value: 30
        - Key: stickiness.lb_cookie.duration_seconds
          Value: 86400
        - Key: slow_start.duration_seconds
          Value: 0
        - Key: stickiness.type
          Value: lb_cookie
        - Key: load_balancing.algorithm.type
          Value: round_robin
      TargetType: instance
      UnhealthyThresholdCount: 2
      VpcId:
        Fn::ImportValue: infrastructureVpcId
  loadBalancerHttpsListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      Certificates:
        - CertificateArn: !Ref certificate
      DefaultActions:
        - TargetGroupArn: !Ref loadBalancerDefaultTargetGroup
          Type: forward
      LoadBalancerArn: !Ref loadBalancer
      Port: 443
      Protocol: HTTPS
    DependsOn:
      - certificate
      - loadBalancerDefaultTargetGroup
      - loadBalancer

  cloudfront:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Aliases:
          - !Ref paramAppHostname
        CustomErrorResponses:
          - ErrorCachingMinTTL: 60
            ErrorCode: 403
            ResponseCode: 404
            ResponsePagePath: /error-pages/404.html
          - ErrorCachingMinTTL: 60
            ErrorCode: 404
            ResponseCode: 404
            ResponsePagePath: /error-pages/404.html
          - ErrorCachingMinTTL: 60
            ErrorCode: 500
            ResponseCode: 500
            ResponsePagePath: /error-pages/500.html
        DefaultCacheBehavior:
          TargetOriginId: elb-payid-1
          ViewerProtocolPolicy: redirect-to-https
          MinTTL: 0
          AllowedMethods:
            - HEAD
            - DELETE
            - POST
            - GET
            - OPTIONS
            - PUT
            - PATCH
          CachedMethods:
            - HEAD
            - GET
          ForwardedValues:
            QueryString: true
            Headers:
              - "*"
            Cookies:
              Forward: all
        Enabled: true
        HttpVersion: http2
        Origins:
          - CustomOriginConfig:
              HTTPSPort: 443
              OriginProtocolPolicy: https-only
              OriginSSLProtocols:
                - TLSv1.2
            DomainName: !GetAtt loadBalancer.DNSName
            Id: elb-payid-1
        PriceClass: PriceClass_All
        ViewerCertificate:
          AcmCertificateArn:
            Ref: certificate
          MinimumProtocolVersion: TLSv1.2_2019
          SslSupportMethod: sni-only
    DependsOn:
      - certificate
      - loadBalancer

  s3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: Private
      BucketName: !Join
        - "-"
        - - "payid-validator"
          - !Select
            - 0
            - !Split
              - "-"
              - !Select
                - 2
                - !Split
                  - "/"
                  - !Ref "AWS::StackId"
      LifecycleConfiguration:
        Rules:
        - AbortIncompleteMultipartUpload:
            DaysAfterInitiation: 1
          Id: DeletePartialUploadsAfter1Day
          NoncurrentVersionExpirationInDays: 30
          Prefix: code-build/
          Status: Enabled
      VersioningConfiguration:
        Status: Enabled

  ssmParameterCloudwatchAgentConfig:
    Type: AWS::SSM::Parameter
    Properties:
      DataType: text
      Description: Config file for the Cloudwatch Agent to store logs
      Name: !Join
        - "-"
        - - "cloudwatch-config"
          - !Select
            - 0
            - !Split
              - "-"
              - !Select
                - 2
                - !Split
                  - "/"
                  - !Ref "AWS::StackId"
      Tier: Standard
      Type: String
      Value: >
        {
          "agent": {
            "run_as_user": "root"
          },
          "logs": {
            "logs_collected": {
              "files": {
                "collect_list": [
                  {
                    "file_path": "/var/log/httpd/access_log",
                    "log_group_name": "access_log",
                    "log_stream_name": "{instance_id}"
                  },
                  {
                    "file_path": "/var/log/httpd/error_log",
                    "log_group_name": "error_log",
                    "log_stream_name": "{instance_id}"
                  },
                  {
                    "file_path": "/var/log/php-fpm/www-error.log",
                    "log_group_name": "php_error_www",
                    "log_stream_name": "{instance_id}"
                  }
                ]
              }
            }
          },
          "metrics": {
            "metrics_collected": {
              "statsd": {
                "metrics_aggregation_interval": 60,
                "metrics_collection_interval": 10,
                "service_address": ":8125"
              }
            }
          }
        }

  iamAppServerRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: inline
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - cloudwatch:PutMetricData
                  - ec2:DescribeVolumes
                  - ec2:DescribeTags
                  - logs:PutLogEvents
                  - logs:DescribeLogStreams
                  - logs:DescribeLogGroups
                  - logs:CreateLogStream
                  - logs:CreateLogGroup
                Resource:
                  - '*'
              - Effect: Allow
                Action:
                  - ssm:GetParameter
                Resource:
                  - !Sub "arn:aws:ssm:*:*:parameter/${ssmParameterCloudwatchAgentConfig}"
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                Resource:
                  - !Ref secretsManagerEtherscanApiKey
                  - !Ref secretsManagerBlockchaincomApiKey
              - Effect: Allow
                Action:
                  - s3:Get*
                  - s3:List*
                Resource:
                  - !GetAtt s3Bucket.Arn
                  - !Sub "${s3Bucket.Arn}/*"
                  - !Sub "arn:aws:s3:::aws-codedeploy-${AWS::Region}/*"
      RoleName: !Join
        - "-"
        - - "app"
          - !Select
            - 0
            - !Split
              - "-"
              - !Select
                - 2
                - !Split
                  - "/"
                  - !Ref "AWS::StackId"
    DependsOn:
      - s3Bucket
      - ssmParameterCloudwatchAgentConfig
      - secretsManagerEtherscanApiKey
      - secretsManagerBlockchaincomApiKey
  iamAppServerInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      InstanceProfileName: !Join
        - "-"
        - - "app"
          - !Select
            - 0
            - !Split
              - "-"
              - !Select
                - 2
                - !Split
                  - "/"
                  - !Ref "AWS::StackId"
      Roles:
        - Ref: iamAppServerRole
    DependsOn:
      - iamAppServerRole

  ec2LaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: !Join
        - "-"
        - - "app"
          - !Select
            - 0
            - !Split
              - "-"
              - !Select
                - 2
                - !Split
                  - "/"
                  - !Ref "AWS::StackId"
      LaunchTemplateData:
        BlockDeviceMappings:
          - DeviceName: /dev/xvda
            Ebs:
              DeleteOnTermination: true
              Encrypted: true
              VolumeSize: 8
              VolumeType: gp2
        EbsOptimized: false
        IamInstanceProfile:
          Arn: !GetAtt iamAppServerInstanceProfile.Arn
        ImageId: !Ref paramAppServerAmiId
        InstanceMarketOptions:
          MarketType: spot
          SpotOptions:
            MaxPrice: 0.0376
        InstanceType: t3a.small
        KeyName: !Ref paramAppServerKeyId
        SecurityGroupIds:
          - Fn::ImportValue: securityGroupEc2
        UserData:
          Fn::Base64: !Sub |
            #!/bin/bash
            yum -y update
            yum -y install ruby
            yum -y install wget
            yum -y install jq

            amazon-linux-extras install -y php7.2
            yum -y install php-gmp
            yum -y install php-mbstring

            yum -y install httpd
            systemctl start httpd
            systemctl enable httpd
            usermod -a -G apache ec2-user
            chown -R ec2-user:apache /var/www
            chmod 2775 /var/www
            find /var/www -type d -exec chmod 2775 {} \;
            find /var/www -type f -exec chmod 0664 {} \;

            # Install CloudWatch Agent
            wget https://s3.${AWS::Region}.amazonaws.com/amazoncloudwatch-agent-${AWS::Region}/amazon_linux/amd64/latest/amazon-cloudwatch-agent.rpm
            rpm -U ./amazon-cloudwatch-agent.rpm
            rm -f ./amazon-cloudwatch-agent.rpm
            /opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-ctl -a fetch-config -m ec2 -s -c ssm:${ssmParameterCloudwatchAgentConfig}

            # Install CodeDeploy Agent
            wget https://aws-codedeploy-${AWS::Region}.s3.amazonaws.com/latest/install
            chmod +x ./install
            sudo ./install auto
            rm -f ./install
    DependsOn:
      - iamAppServerRole
      - iamAppServerInstanceProfile

  ec2AutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      AutoScalingGroupName: !Join
        - "-"
        - - "app"
          - !Select
            - 0
            - !Split
              - "-"
              - !Select
                - 2
                - !Split
                  - "/"
                  - !Ref "AWS::StackId"
      AvailabilityZones:
        - !Select
          - 0
          - Fn::GetAZs: !Ref 'AWS::Region'
        - !Select
          - 1
          - Fn::GetAZs: !Ref 'AWS::Region'
        - !Select
          - 2
          - Fn::GetAZs: !Ref 'AWS::Region'
      Cooldown: 120
      DesiredCapacity: 2
      HealthCheckGracePeriod: 240
      HealthCheckType: EC2
      MaxSize: 4
      MinSize: 2
      LaunchTemplate:
        LaunchTemplateId:
          !Ref ec2LaunchTemplate
        Version:
          !GetAtt ec2LaunchTemplate.LatestVersionNumber
      TargetGroupARNs:
        - Ref: loadBalancerDefaultTargetGroup
      TerminationPolicies:
        - Default
      VPCZoneIdentifier:
        - Fn::ImportValue: infrastructureVpcSubnetIdA
        - Fn::ImportValue: infrastructureVpcSubnetIdB
        - Fn::ImportValue: infrastructureVpcSubnetIdC
    DependsOn:
      - ec2LaunchTemplate

  route53RecordSet:
    Type: AWS::Route53::RecordSet
    Properties:
      AliasTarget:
        HostedZoneId: Z2FDTNDATAQYW2
        DNSName: !GetAtt cloudfront.DomainName
      HostedZoneId: !Ref paramHostedRoute53ZoneId
      Name: !Sub "${paramAppHostname}."
      Type: A
    DependsOn:
      - cloudfront

  cloudwatchLogsLogGroupApacheAccessLog:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: access_log
      RetentionInDays: 7
  cloudwatchLogsLogGroupApacheErrorLog:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: error_log
      RetentionInDays: 7
  cloudwatchLogsLogGroupPhpErrorLog:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: php_error_www
      RetentionInDays: 7

  secretsManagerEtherscanApiKey:
    Type: AWS::SecretsManager::Secret
    Properties:
      SecretString: !Sub '${paramEtherscanApiKey}'
      Name: etherscan
  secretsManagerBlockchaincomApiKey:
    Type: AWS::SecretsManager::Secret
    Properties:
      SecretString: !Sub '${paramBlockchaincomApiKey}'
      Name: blockchain

Outputs:
  s3Bucket:
    Description: S3 Bucket name
    Value: !Ref s3Bucket
    Export:
      Name: s3Bucket
  ec2AutoScalingGroup:
    Description: EC2 Autoscaling Group name
    Value: !Ref ec2AutoScalingGroup
    Export:
      Name: ec2AutoScalingGroup
  appHostname:
    Description: The hostname of where the app is hosted.
    Value: !Ref paramAppHostname
    Export:
      Name: appHostname