version: 0.2

env:
  variables:
     NODE_ENV: "production"

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      # Install composer
      - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
      - php composer-setup.php
      - php -r "unlink('composer-setup.php');"
      - mv composer.phar /usr/local/bin/composer
  build:
    commands:
      # Have composer install the PHP dependencies
      - cd dist && composer install --no-progress --no-suggest && rm -f composer.* && cd -
      # Yarn to install tailwindcss now to compiles the CSS
      - yarn add tailwindcss --dev
      # Build/compile the production CSS now
      - npm run build:css
      - npm run cachebust
      # Remove the node_modules directory now that we are done building to make the artifact smaller
      - rm -Rf node_modules
      # No need to keep the "src" directory for a build
      - rm -Rf src

artifacts:
  files:
    - '**/*'