version: 0.2

env:
  variables:
     NODE_ENV: "production"

phases:
  install:
    runtime-versions:
      nodejs: 10
      php: 7.4
    commands:
      - PYTHON=python2 amazon-linux-extras enable php7.4
      - yum -y install php-gmp
      - yum -y install php-mbstring
      - yum -y update
      # Install composer
      - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
      - php composer-setup.php
      - php -r "unlink('composer-setup.php');"
      - mv composer.phar /usr/local/bin/composer
      # Scan this dir for additional .ini files => /root/.phpenv/versions/7.4.7/etc/conf.d
      - rpm -ql php-gmp
  build:
    commands:
      - sed -i "s/<% RELEASE_HASH %>/$CODEBUILD_RESOLVED_SOURCE_VERSION/g" dist/index.php
      # Have composer install the PHP dependencies
      - cd dist && composer install --no-progress --no-suggest && rm -f composer.* && cd -
      # Install dependencies
      - npm install
      # Build/compile the production CSS now
      - npm run build:css
      - npm run cachebust
      # Remove the node_modules directory now that we are done building to make the artifact smaller
      - rm -Rf node_modules
      # No need to keep the "src" directory for a build
      - rm -Rf src

artifacts:
  files:
    - '**/*'