version: 0.2

env:
  variables:
     NODE_ENV: "production"

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - echo Entered the install phase...
      # Setup Yarn
      - curl --silent --location https://dl.yarnpkg.com/rpm/yarn.repo | tee /etc/yum.repos.d/yarn.repo
      - yum -y install yarn
      #Install composer
      - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php')"
      - php composer-setup.php
      - php -r "unlink('composer-setup.php');"
      - mv composer.phar /usr/local/bin/composer
  pre_build:
    commands:
      - echo Entered the pre_build pahse...
      - yarn install
  build:
    commands:
      - Entered the build phase...
      # Have composer install the PHP dependencies
      - cd dist/
      - composer install --no-progress --no-suggest
      - rm -f composer.*
      - cd ../
      # Yarn to install tailwindcss now to compiles the CSS
      - yarn add tailwindcss --dev
      # Build/compile the production CSS now
      - npm run build:css

artifacts:
  files:
    - '**/*'
  name: app-$(date +%Y-%m-%d-%H-%M-%S)
  discard-paths: no
  base-directory: dist